---
apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-new-index
data:
  actions.yaml: |-
    ---
    actions:
      1:
        action: create_index
        description: "Create a new index for the next day on the hot box"
        options:
          name: "<logstash-{now/d+1d}>"
          extra_settings:
            number_of_shards: 5
            number_of_replicas: 1
            index.routing.allocation.require.box_type: hot
  config.yaml: |-
    ---
    client:
      hosts:
        - elasticsearch-client
      port: 9200
      url_prefix:
      use_ssl: false
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: false
      http_auth:
      timeout: 30
      master_only: false
    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
