---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data-hot
  labels:
    app: elasticsearch
    role: data
    type: hot
spec:
  clusterIP: None
  selector:
    app: elasticsearch
    role: data
    type: hot
  ports:
    - port: 9300
      name: transport
