---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.2.0
          ports:
            - containerPort: 5775
              protocol: UDP
              name: agent-zipkin
            - containerPort: 6831
              protocol: UDP
              name: agent-compact
            - containerPort: 6832
              protocol: UDP
              name: agent-binary
            - containerPort: 16686
              name: frontend
            - containerPort: 9411
              name: zipkin-endpoint
            - containerPort: 5778
              name: config
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
          readinessProbe:
            httpGet:
              path: "/"
              port: 16686
            initialDelaySeconds: 5
