---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  labels:
    app: jaeger
    component: agent
spec:
  type: LoadBalancer
  selector:
    app: jaeger
  ports:
    - port: 5775
      protocol: UDP
      name: zipkin
    - port: 6831
      protocol: UDP
      name: compact
    - port: 6832
      protocol: UDP
      name: binary
