---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  labels:
    app: jaeger
    component: collector
spec:
  selector:
    app: jaeger
    component: collector
  ports:
    - port: 14267
      name: tchannel
    - port: 14268
      name: http
    - port: 9411
      name: zipkin
