---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: jaeger
    component: zipkin-endpoint
spec:
  selector:
    app: jaeger
    component: collector
  ports:
    - port: 9411
