version: "3"

# More info at https://github.com/AdguardTeam/AdGuardHome and https://adguard.com/en/adguard-home/overview.html
services:
   adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    ports:
      - 53:53
      - 67:67/udp
      - 68:68
      - 80:80/tcp
      - 443:443
      - 784:784/udp
      - 853:853
      - 3000:3000/tcp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Europe/Zagreb'
    volumes:
      - ./conf:/conf
      - ./work:/work
    restart: unless-stopped
